### ISSUE TITLE
Rodar o programa

### ISSUE THREAD

**Issue by Voctor-367** [maicon15rp/Music-Lyric-Download#2]
O passo a passo mostrado abre o script no vs code.

Para rodar o programa em linha de comando, deve-se executar o comando : python Pesquisarmusica.py

**Comment by maicon15rp** [comment]
Adicionei esses detalhes, tornando mais explícita a forma como se deve executar o arquivo `Pesquisarmusica.py`. Especificando o uso do prefixo `py` antes do nome do arquivo. Além disso, considerei variações como `python PesquisarMusica.py`, `python3 PesquisarMusica.py` ou `py3 PesquisarMusica.py`
